"use client";
import { useState } from "react";
import { ArrowRight, Check, RotateCcw, Zap } from "lucide-react";

const answers = ["Poți cumpăra mai mult", "Puterea ta de cumpărare scade", "Nu se schimbă nimic"];
export function LessonPreview({ initialAnswer = null }: { initialAnswer?: number | null }) {
  const [answer, setAnswer] = useState<number | null>(initialAnswer);
  const correct = answer === 1;
  return <div className="quiz"><div className="quiz-meta"><span>ECONOMIE, PE SCURT</span><span>2 / 5</span></div><div className="quiz-progress" role="progressbar" aria-label="Progresul lecției demonstrative" aria-valuenow={2} aria-valuemin={0} aria-valuemax={5}><span/></div><h3>Ce este inflația?</h3><p className="quiz-question">Dacă prețurile cresc, iar venitul tău rămâne la fel, ce se întâmplă?</p><div className="quiz-answers" role="group" aria-label="Alege un răspuns">{answers.map((text, i) => <button key={text} className={`quiz-answer ${answer === i ? correct ? "is-correct" : "is-wrong" : ""}`} aria-pressed={answer === i} onClick={() => setAnswer(i)}><span className="answer-letter">{String.fromCharCode(65 + i)}</span><span>{text}</span>{answer === i && correct && <Check size={18}/>}</button>)}</div><div className={`quiz-feedback ${answer === null ? "is-idle" : correct ? "is-correct" : "is-wrong"}`} aria-live="polite">{answer === null ? <><span className="feedback-icon"><ArrowRight size={17}/></span><div><strong>Ce crezi?</strong><p>Alege un răspuns. Învățăm din fiecare încercare.</p></div></> : <><span className="feedback-icon">{correct ? <Check size={17}/> : <RotateCcw size={17}/>}</span><div><strong>{correct ? "Exact. Ai prins ideea!" : "Mai încearcă. Ești aici să înveți."}</strong><p>{correct ? "Cu aceeași sumă cumperi mai puține lucruri. Asta înseamnă că puterea de cumpărare scade." : "Prețurile mai mari înseamnă că aceiași bani nu mai ajung pentru la fel de multe lucruri."}</p></div></>}</div><div className="quiz-footer"><span><Zap size={15}/>{correct ? "+20 XP · Demo" : "Un concept. Un pas înainte."}</span>{answer !== null && <button onClick={() => setAnswer(null)} aria-label="Resetează răspunsul"><RotateCcw size={14}/> Mai încearcă</button>}</div></div>;
}
