import { afterEach, describe, expect, it, vi } from "vitest";
import * as engine from "../src/lib/progress";
import { gamificationConfig, GamificationConfigSchema } from "../src/content/gamification-config";
import { dailyChallenges, validateDailyChallenges } from "../src/content/daily-challenges";
import { achievements } from "../src/content/achievements";
import { getReadyLessons } from "../src/content/lessons";
import { ProgressSchema, XpEventSchema } from "../src/lib/progress-schema";
import { getOffsetNow } from "../src/lib/clock";
import { addCalendarDays, getBucharestDateKey } from "../src/lib/bucharest-date";
import { shuffleOptions, getDisplayOptions, validateAnswerPositions } from "../src/lib/lesson-options";
import type { LessonSessionResult, ProgressState, XpEvent, XpEventType } from "../src/types/progress";
import type { ReadyLesson } from "../src/types/learning";
const now = new Date("2026-10-04T12:00:00Z"), lesson = getReadyLessons()[0];
const empty = () => engine.createEmptyProgress(now);
const onDay = (key: string) => new Date(key + "T12:00:00Z");
function session(score: number, id = "first", content: ReadyLesson = lesson): LessonSessionResult {
  return { lessonId: content.id, sessionId: id, answers: content.screens.filter(engine.isAnswerScreen).map((s, i) => ({ screenId: s.id, selectedOptionId: i < score ? engine.getCorrectAnswerId(s)! : "wrong" })) };
}
const subtotal = (result: engineReturn) => result.newEvents.filter(e => e.type.startsWith("lesson_")).reduce((sum, e) => sum + e.amount, 0);
type engineReturn = ReturnType<typeof engine.completeLessonSession>;
function event(id: string, amount: number, type: XpEventType = "lesson_completion", key = "2026-10-04"): XpEvent { return { id, amount, type, createdAt: now.toISOString(), bucharestDateKey: key }; }
function goalAction(p: ProgressState) { return engine.finishAction(p, p, [], now); }
function activity(p: ProgressState, key: string) { const date = onDay(key), normalized = engine.reconcileCalendar(p, date); return engine.finishAction(p, normalized, [], date, true).progress; }
function curriculum(size: number): ReadyLesson[] { return Array.from({ length: size }, (_, i) => ({ ...lesson, id: `test-${i}`, categoryId: "test-category" })); }
function completeFixtures(p: ProgressState, lessons: ReadyLesson[]) { return { ...p, lessonStats: Object.fromEntries(lessons.map(l => [l.id, { completed: true, bestFirstTryCorrect: 0, questionCount: 9, perfectEver: false, completionCount: 1, sessionIds: ["fixture"] }])) }; }
afterEach(() => vi.unstubAllGlobals());
describe("config and progress schema", () => {
  it("starts completely clean with level 1 and one freeze", () => { const p = empty(); expect(ProgressSchema.parse(p)).toEqual(p); expect(engine.getTotalXp(p)).toBe(0); expect(engine.getCurrentLevel(0).title).toBe("Money Beginner"); expect(p.freezeBalance).toBe(1); expect(engine.getCompletedLessonCount(p)).toBe(0); expect(Object.keys(p.achievementUnlocks)).toHaveLength(0); expect(engine.getDailyGoalState(p, "2026-10-04").current).toBe(0); expect(achievements).toHaveLength(21); });
  it.each([{}, { version: 1, totalXp: 900 }, { version: 0, xp: 720 }, null])("discards old data %j", value => expect(engine.normalizeProgress(value, now)).toEqual(empty()));
  it("normalizes partial v2 and removes invalid/duplicate journal entries", () => { const e = event("one", 20); const p = engine.normalizeProgress({ version: 2, xp_events: [e, e, { ...e, id: "bad", amount: -1 }], freezeBalance: 999 }, now); expect(engine.getTotalXp(p)).toBe(20); expect(p.freezeBalance).toBe(2); expect(p.xp_events).toHaveLength(1); });
  it.each([-1, 1.5])("rejects invalid reward amount %s", xp => expect(() => GamificationConfigSchema.parse({ ...gamificationConfig, rewards: { ...gamificationConfig.rewards, lesson_completion: { ...gamificationConfig.rewards.lesson_completion, xp } } })).toThrow());
  it("rejects levels, milestones, goal, freeze cap and insufficient challenges", () => {
    for (const override of [{ levels: [gamificationConfig.levels[0], gamificationConfig.levels[0]] }, { streakMilestones: [{ days: 7, xp: 1 }, { days: 3, xp: 1 }] }, { streakMilestones: [{ days: 3, xp: 1 }, { days: 3, xp: 1 }] }, { dailyGoalTargetXp: 0 }, { freeze: { initialBalance: 1, weeklyGrant: 2, maxBalance: 1 } }, { dailyChallengeCount: 30 }]) expect(() => GamificationConfigSchema.parse({ ...gamificationConfig, ...override })).toThrow();
  });
  it("validates journal fields", () => { for (const override of [{ amount: -1 }, { amount: 0.5 }, { id: "" }, { type: "unknown" }, { createdAt: "yesterday" }, { bucharestDateKey: "2026-02-30" }]) expect(XpEventSchema.safeParse({ ...event("valid", 4), ...override }).success).toBe(false); });
  it("never mutates or rewrites previous events", () => { const p = { ...empty(), xp_events: [event("one", 4)] }; const next = engine.appendXpEvents(p, [event("one", 100), event("two", 20)]); expect(p.xp_events).toHaveLength(1); expect(next.xp_events[0].amount).toBe(4); expect(engine.getTotalXp(next)).toBe(24); });
  it("sums duplicate IDs just once even before normalization", () => expect(engine.getTotalXp({ ...empty(), xp_events: [event("one", 4), event("one", 4)] })).toBe(4));
});
describe("lesson rewards and replay", () => {
  it.each([[7, 48], [9, 71], [0, 20]])("first %i/9 lesson subtotal is %i", (score, xp) => { const result = engine.completeLessonSession(empty(), session(score), now); expect(subtotal(result)).toBe(xp); expect(result.lesson?.score).toBe(score); expect(result.progress.lessonStats[lesson.id].completed).toBe(true); });
  it("question XP is pending and abandoned sessions do not change progress", () => { const p = empty(); expect(engine.getPendingQuestionXp(p, lesson.id, true)).toBe(4); expect(engine.getPendingQuestionXp(p, lesson.id, false)).toBe(0); expect(engine.getTotalXp(p)).toBe(0); expect(p.xp_events).toHaveLength(0); });
  it("requires all first attempts", () => expect(() => engine.completeLessonSession(empty(), { ...session(9), answers: session(9).answers.slice(0, 4) }, now)).toThrow());
  it("double final submit adds no XP or completion count", () => { const first = engine.completeLessonSession(empty(), session(9), now); const again = engine.completeLessonSession(first.progress, session(9), now); expect(again.xpGained).toBe(0); expect(again.progress.lessonStats[lesson.id].completionCount).toBe(1); expect(engine.getTotalXp(again.progress)).toBe(81); });
  it.each([[6, 8, 8], [4, 9, 10], [8, 7, 0], [8, 8, 0]])("replay %i to %i rewards %i", (first, score, xp) => { const p = engine.completeLessonSession(empty(), session(first), now).progress; const result = engine.completeLessonSession(p, session(score, "replay"), now); expect(subtotal(result)).toBe(xp); expect(result.lesson?.improvementXp).toBe(xp); expect(result.newEvents.some(e => e.type === "lesson_perfect")).toBe(false); expect(engine.getPendingQuestionXp(p, lesson.id, true)).toBe(0); });
  it("successive improvements reward only increasing best scores", () => { let p = engine.completeLessonSession(empty(), session(6), now).progress; let r = engine.completeLessonSession(p, session(8, "second"), now); expect(subtotal(r)).toBe(8); p = r.progress; r = engine.completeLessonSession(p, session(9, "third"), now); expect(subtotal(r)).toBe(4); expect(subtotal(engine.completeLessonSession(r.progress, session(9, "fourth"), now))).toBe(0); });
  it("replay perfect unlocks achievement but never retroactive perfect XP", () => { const p = engine.completeLessonSession(empty(), session(4), now).progress; const r = engine.completeLessonSession(p, session(9, "replay"), now); expect(r.progress.achievementUnlocks.perfectionist).toBeTruthy(); expect(r.progress.xp_events.some(e => e.type === "lesson_perfect")).toBe(false); });
  it("uses first selected answer and semantic screen keys", () => { const original = session(0); const r = engine.completeLessonSession(empty(), { ...original, answers: [...original.answers, ...session(9).answers] }, now); expect(r.lesson?.score).toBe(0); const first = engine.completeLessonSession(empty(), session(9), now); const replay = engine.completeLessonSession(first.progress, session(9, "replay"), now); expect(replay.progress.uniqueCorrectAnswers).toHaveLength(9); });
  it("assigns all rewards to completion day after midnight", () => { const start = new Date("2026-10-04T20:58:00Z"), finish = new Date("2026-10-04T21:02:00Z"); const r = engine.completeLessonSession(engine.createEmptyProgress(start), session(7), finish); expect(r.newEvents.every(e => e.bucharestDateKey === "2026-10-05")).toBe(true); expect(r.progress.activityDates).toEqual(["2026-10-05"]); });
});
describe("levels", () => {
  it.each([[0, 1], [149, 1], [150, 2], [399, 2], [400, 3], [799, 3], [800, 4], [1399, 4], [1400, 5], [2199, 5], [2200, 6], [3199, 6], [3200, 7], [4499, 7], [4500, 8], [10000, 8]])("%i XP gives level %i", (xp, level) => expect(engine.getCurrentLevel(xp).level).toBe(level));
  it("1050 means 250 / 600 within current level", () => expect(engine.getLevelProgress(1050)).toMatchObject({ earned: 250, target: 600, current: { minXp: 800 }, next: { minXp: 1400 } }));
  it("max level has a finite 100% bar", () => expect(engine.getLevelProgress(10000)).toMatchObject({ isMax: true, percent: 100, remainingXp: 0 }));
  it("multi-jump returns one effect ending at final level", () => { const r = engine.finishAction(empty(), empty(), [event("jump", 850, "debug_adjustment")], now); expect(r.levelUpCount).toBe(3); expect(r.levelUp?.to.title).toBe("Money Smart"); expect(r.progress.pendingLevelUp?.to.level).toBe(4); });
});
describe("daily goal and challenges", () => {
  it.each([[49, false, 49], [50, true, 60]])("qualifying %i triggers goal %s", (amount, reached, total) => { const p = { ...empty(), xp_events: [event("qualifying", amount)] }; const r = goalAction(p); expect(r.dailyGoalCompleted).toBe(reached); expect(engine.getTotalXp(r.progress)).toBe(total); expect(engine.getQualifyingXpForDate(r.progress, "2026-10-04")).toBe(amount); expect(goalAction(r.progress).xpGained).toBe(0); });
  it("streak reward never triggers its own daily goal", () => { const p = { ...empty(), xp_events: [event("base", 20), event("streak", 300, "streak_milestone")] }; expect(engine.getTotalXp(p)).toBe(320); expect(goalAction(p).dailyGoalCompleted).toBe(false); expect(engine.getQualifyingXpForDate(p, "2026-10-04")).toBe(20); });
  it("debug affects total/level but not goal, streak or earned-XP achievements", () => { const r = engine.addDebugXp(empty(), "debug", now); expect(engine.getTotalXp(r.progress)).toBe(100); expect(engine.getEarnedXpExcludingDebug(r.progress)).toBe(0); expect(engine.getDailyGoalState(r.progress, "2026-10-04").current).toBe(0); expect(r.progress.activityDates).toHaveLength(0); expect(r.progress.achievementUnlocks["xp-100"]).toBeUndefined(); });
  it("correct daily rewards 15 and wrong daily rewards 0, both record activity", () => { const c = engine.selectDailyChallenge("2026-10-04"); const right = engine.completeDailyChallenge(empty(), c.correctOptionId, now), wrong = engine.completeDailyChallenge(empty(), c.options.find(o => o.id !== c.correctOptionId)!.id, now); expect(right.xpGained).toBe(15); expect(wrong.xpGained).toBe(0); for (const r of [right, wrong]) { expect(r.progress.activityDates).toEqual(["2026-10-04"]); expect(r.progress.achievementUnlocks["first-challenge"]).toBeTruthy(); expect(engine.completeDailyChallenge(r.progress, c.correctOptionId, now).xpGained).toBe(0); } });
  it("48 then daily correct is 73 including the goal reward", () => { const first = engine.completeLessonSession(empty(), session(7), now); expect(engine.getDailyGoalState(first.progress, "2026-10-04").current).toBe(48); const daily = engine.completeDailyChallenge(first.progress, engine.selectDailyChallenge("2026-10-04").correctOptionId, now); expect(daily.xpGained).toBe(25); expect(engine.getTotalXp(daily.progress)).toBe(73); expect(engine.getQualifyingXpForDate(daily.progress, "2026-10-04")).toBe(63); });
  it("contains exactly 40 valid unique challenges", () => { expect(dailyChallenges).toHaveLength(40); expect(validateDailyChallenges(dailyChallenges)).toEqual(dailyChallenges); expect(() => validateDailyChallenges(dailyChallenges.slice(1))).toThrow(); expect(() => validateDailyChallenges([...dailyChallenges.slice(1), dailyChallenges[1]])).toThrow(); expect(() => validateDailyChallenges(dailyChallenges.map((c, i) => i ? c : { ...c, correctOptionId: "missing" }))).toThrow(); expect(() => validateDailyChallenges(dailyChallenges.map((c, i) => i ? c : { ...c, explanation: "" }))).toThrow(); });
  it("31-day month has no repeats and selection survives reload", () => { const ids = Array.from({ length: 31 }, (_, i) => engine.selectDailyChallenge(`2026-10-${String(i + 1).padStart(2, "0")}`).id); expect(new Set(ids).size).toBe(31); expect(engine.selectDailyChallenge("2026-10-04")).toEqual(engine.selectDailyChallenge("2026-10-04")); expect(engine.selectDailyChallenge("2026-11-04").id).not.toBe(ids[3]); });
  it("answered challenge survives normalized reload and cannot be retried", () => { const c = engine.selectDailyChallenge("2026-10-04"), r = engine.completeDailyChallenge(empty(), c.correctOptionId, now); const p = engine.normalizeProgress(JSON.parse(JSON.stringify(r.progress)), now); expect(p.dailyChallenges).toEqual(r.progress.dailyChallenges); expect(engine.getDailyChallengeFor(p, "2026-10-04").id).toBe(c.id); expect(engine.completeDailyChallenge(p, c.options[0].id, now).newEvents).toHaveLength(0); });
});
describe("Bucharest clock, streak and freezes", () => {
  it.each([["2026-03-28T22:30:00Z", "2026-03-29"], ["2026-03-29T21:30:00Z", "2026-03-30"], ["2026-10-24T21:30:00Z", "2026-10-25"], ["2026-10-25T22:30:00Z", "2026-10-26"]])("DST %s => %s", (timestamp, key) => expect(getBucharestDateKey(new Date(timestamp))).toBe(key));
  it("same-day activity counts only once", () => { const p = activity(activity(empty(), "2026-10-05"), "2026-10-05"); expect(engine.calculateStreak(p, "2026-10-05").current).toBe(1); });
  it("normal consecutive days", () => { const p = activity(activity(empty(), "2026-10-05"), "2026-10-06"); expect(engine.calculateStreak(p, "2026-10-06").current).toBe(2); });
  it("one missed day consumes a freeze without counting it", () => { const p = activity(activity(empty(), "2026-10-05"), "2026-10-07"); expect(p.freezeDates).toEqual(["2026-10-06"]); expect(engine.calculateStreak(p, "2026-10-07").current).toBe(2); });
  it("load can protect yesterday without creating an activity or XP", () => { const first = activity(empty(), "2026-10-05"), p = engine.normalizeProgress(first, onDay("2026-10-07")); expect(p.freezeDates).toEqual(["2026-10-06"]); expect(p.activityDates).toEqual(["2026-10-05"]); expect(engine.calculateStreak(p, "2026-10-07").current).toBe(1); expect(engine.getTotalXp(p)).toBe(0); });
  it("two missed days break with no double-freeze chain", () => { const p = activity(activity(empty(), "2026-10-05"), "2026-10-08"); expect(p.freezeDates).toHaveLength(0); expect(engine.calculateStreak(p, "2026-10-08").current).toBe(1); });
  it("opening between two misses cannot chain freezes", () => { let p = activity(empty(), "2026-10-05"); p = engine.normalizeProgress(p, onDay("2026-10-07")); p = activity(p, "2026-10-08"); expect(p.freezeDates).toEqual(["2026-10-06"]); expect(engine.calculateStreak(p, "2026-10-08").current).toBe(1); });
  it("two isolated freeze days separated by activity are valid", () => { let p = activity(empty(), "2026-10-05"); p = activity(p, "2026-10-07"); p = activity(p, "2026-10-09"); expect(p.freezeDates).toEqual(["2026-10-06", "2026-10-08"]); expect(engine.calculateStreak(p, "2026-10-09").current).toBe(3); expect(p.freezeBalance).toBe(0); });
  it.each([[0, 1], [1, 2], [2, 2]])("Monday grants balance %i => %i once", (balance, expected) => { const p = engine.reconcileCalendar({ ...empty(), freezeBalance: balance }, onDay("2026-10-05")); expect(p.freezeBalance).toBe(expected); expect(engine.reconcileCalendar(p, onDay("2026-10-05")).freezeBalance).toBe(expected); });
  it("no available freeze means a one-day gap breaks", () => { let p = activity(empty(), "2026-10-05"); p = activity({ ...p, freezeBalance: 0 }, "2026-10-07"); expect(p.freezeDates).toHaveLength(0); expect(engine.calculateStreak(p, "2026-10-07").current).toBe(1); });
  it("longest remains after current streak breaks", () => { let p = empty(); for (const key of ["2026-10-05", "2026-10-06", "2026-10-07", "2026-10-11"]) p = activity(p, key); expect(engine.calculateStreak(p, "2026-10-11")).toMatchObject({ current: 1, longest: 3 }); });
  it.each([[3, 25], [7, 75], [14, 150], [30, 300]])("milestone %i rewards %i once for the lifetime", (days, xp) => { let p = engine.createEmptyProgress(onDay("2026-09-01")); for (let i = 0; i < days; i++) p = activity(p, addCalendarDays("2026-09-01", i)); expect(p.xp_events.filter(e => e.id === `streak-milestone:${days}`)).toEqual([expect.objectContaining({ amount: xp })]); for (let i = 0; i < days; i++) p = activity(p, addCalendarDays("2026-11-01", i)); expect(p.xp_events.filter(e => e.id === `streak-milestone:${days}`)).toHaveLength(1); });
  it("clock rollback cannot answer an old daily again", () => { const futureNow = onDay("2026-10-10"); let p = engine.normalizeProgress(empty(), futureNow); p = engine.completeDailyChallenge(p, engine.selectDailyChallenge("2026-10-10").correctOptionId, futureNow).progress; const r = engine.completeDailyChallenge(p, engine.selectDailyChallenge("2026-10-10").correctOptionId, onDay("2026-10-08")); expect(r.xpGained).toBe(0); expect(r.progress.maxSeenDateKey).toBe("2026-10-10"); expect(Object.keys(r.progress.dailyChallenges)).toEqual(["2026-10-10"]); });
  it("last seven days distinguish real activity, freeze, today and misses", () => { const p = { ...empty(), activityDates: ["2026-10-02"], freezeDates: ["2026-10-03"] }; expect(engine.getLast7Days(p, "2026-10-04").slice(-3).map(d => d.state)).toEqual(["activity", "freeze", "today"]); });
});
describe("achievements and simulator", () => {
  it("first lesson and perfect achievements unlock only from real completion", () => { const r = engine.completeLessonSession(empty(), session(9), now); expect(r.achievementsUnlocked).toContain("first-step"); expect(r.achievementsUnlocked).toContain("perfectionist"); });
  it("three unique perfect lessons", () => { let p = empty(); for (const l of getReadyLessons().slice(0, 3)) p = engine.completeLessonSession(p, session(9, l.id, l), now).progress; expect(p.achievementUnlocks["three-perfect"]).toBeTruthy(); });
  it.each([1, 2, 3, 4])("Specialist category size %i", size => { const lessons = curriculum(size), p = engine.evaluateAchievements(completeFixtures(empty(), lessons), now, lessons); expect(Boolean(p.achievementUnlocks.specialist)).toBe(size >= 3); });
  it("unlocked achievements stay unlocked when curriculum grows", () => { const lessons = curriculum(3), unlocked = engine.evaluateAchievements(completeFixtures(empty(), lessons), now, lessons); const expanded = engine.evaluateAchievements(unlocked, onDay("2026-10-05"), curriculum(4)); expect(expanded.achievementUnlocks.specialist).toEqual(unlocked.achievementUnlocks.specialist); });
  it("seven distinct daily goals and ten correct challenges unlock", () => { const p = { ...empty(), xp_events: Array.from({ length: 7 }, (_, i) => event(`goal-${i}`, 10, "daily_goal_bonus", addCalendarDays("2026-09-01", i))), dailyChallenges: Object.fromEntries(Array.from({ length: 10 }, (_, i) => [addCalendarDays("2026-09-01", i), { challengeId: dailyChallenges[i].id, selectedOptionId: dailyChallenges[i].correctOptionId, correct: true, answeredAt: now.toISOString() }])) }; const next = engine.evaluateAchievements(p, now); expect(next.achievementUnlocks["daily-goals-seven"]).toBeTruthy(); expect(next.achievementUnlocks["ten-challenges"]).toBeTruthy(); });
  it("simulator grants 100 once, unlocks Prima lună, no goal or activity", () => { const r = engine.completeSimulator(empty(), "simulator", now); expect(r.xpGained).toBe(100); expect(r.progress.achievementUnlocks["first-month"]).toBeTruthy(); expect(r.progress.activityDates).toHaveLength(0); expect(engine.getQualifyingXpForDate(r.progress, "2026-10-04")).toBe(0); expect(engine.completeSimulator(r.progress, "simulator", now).xpGained).toBe(0); });
  it("simulator UI completion uses the same reward engine", () => { const r = engine.saveSimulationStep(empty(), { step: 5, balance: 2000, savings: 500, history: ["choice"] }, now); expect(r.xpGained).toBe(100); expect(r.progress.simulation.step).toBe(5); });
  it("all subject references point to stable curriculum IDs", () => { for (const id of ["primul-buget", "scorul-de-credit"]) { const l = getReadyLessons().find(l => l.id === id)!; const r = engine.completeLessonSession(empty(), session(9, id, l), now); expect(r.progress.achievementUnlocks[id === "primul-buget" ? "budget-ready" : "calm-credit"]).toBeTruthy(); } });
});
describe("browser storage boundary", () => {
  function storage(raw: string | null) { const values = new Map<string, string>(); if (raw !== null) values.set(engine.PROGRESS_STORAGE_KEY, raw); const setItem = vi.fn((key: string, value: string) => values.set(key, value)); vi.stubGlobal("window", { localStorage: { getItem: (key: string) => values.get(key) ?? null, setItem } }); return { values, setItem }; }
  it("old version resets once, v2 reload keeps earned progress", () => { const s = storage(JSON.stringify({ version: 1, totalXp: 900 })); const initial = engine.loadProgress(now); expect(initial.changed).toBe(true); expect(engine.saveProgress(initial.progress)).toBe(true); const earned = engine.completeLessonSession(initial.progress, session(7), now).progress; engine.saveProgress(earned); const reloaded = engine.loadProgress(now); expect(engine.getTotalXp(reloaded.progress)).toBe(48); expect(reloaded.changed).toBe(false); expect(s.setItem).toHaveBeenCalledTimes(2); });
  it("corrupt JSON loads safely", () => { storage("{broken"); expect(engine.loadProgress(now).progress).toEqual(empty()); });
  it("future schema is never overwritten even after an action", () => { const raw = JSON.stringify({ version: 3, precious: "future" }), s = storage(raw); const loaded = engine.loadProgress(now); expect(loaded.readOnly).toBe(true); expect(loaded.changed).toBe(false); expect(engine.saveProgress(engine.addDebugXp(loaded.progress, "test", now).progress)).toBe(false); expect(s.values.get(engine.PROGRESS_STORAGE_KEY)).toBe(raw); expect(s.setItem).not.toHaveBeenCalled(); });
  it("storage denied is safe", () => { vi.stubGlobal("window", { get localStorage() { throw new Error("denied"); } }); expect(engine.loadProgress(now).persisted).toBe(false); expect(engine.saveProgress(empty())).toBe(false); });
});
describe("existing content and stable shuffle integration", () => {
  it("all ready lessons retain valid balanced static options", () => { for (const l of getReadyLessons()) expect(() => validateAnswerPositions(l)).not.toThrow(); });
  it("seeded options survive feedback/modal rerenders and preserve semantic correctness", () => { const screen = lesson.screens.find(s => s.type === "variante")!; const original = JSON.stringify(screen); const correct = engine.getCorrectAnswerId(screen); const first = getDisplayOptions(screen, lesson.id, "same-session"); for (let i = 0; i < 10; i++) expect(getDisplayOptions(screen, lesson.id, "same-session")).toEqual(first); expect(first.some(o => o.id === correct)).toBe(true); expect(JSON.stringify(screen)).toBe(original); expect(new Set(Array.from({ length: 10 }, (_, i) => getDisplayOptions(screen, lesson.id, String(i)).map(o => o.id).join())).size).toBeGreaterThan(1); });
  it("true/false and explicit semantic-order exceptions stay fixed", () => { const tf = lesson.screens.find(s => s.type === "adevarat_fals")!; expect(getDisplayOptions(tf, lesson.id, "seed").map(o => o.id)).toEqual(["true", "false"]); const screen = lesson.screens.find(s => s.type === "variante")!; if (screen.type !== "variante") throw new Error("fixture"); expect(getDisplayOptions({ ...screen, shuffle: false }, lesson.id, "seed")).toEqual(screen.options); });
  it("shuffle never mutates input", () => { const ids = ["a", "b", "c"]; shuffleOptions(ids, "seed"); expect(ids).toEqual(["a", "b", "c"]); });
});
describe("notification acknowledgements and virtual calendar", () => {
  it("seen achievement toasts persist without changing XP or unlock dates", () => { const unlocked = engine.completeLessonSession(empty(), session(9), now).progress; const p = engine.markAchievementToastSeen(engine.markAchievementToastSeen(unlocked, "first-step"), "first-step"); expect(p.seenAchievementToastIds).toEqual(["first-step"]); expect(engine.normalizeProgress(p, now).seenAchievementToastIds).toEqual(["first-step"]); expect(p.achievementUnlocks).toEqual(unlocked.achievementUnlocks); expect(engine.getTotalXp(p)).toBe(81); });
  it("freeze notifications are acknowledged once", () => { const p = engine.markFreezeToastSeen(engine.markFreezeToastSeen(empty(), "2026-10-03"), "2026-10-03"); expect(p.seenFreezeToastDates).toEqual(["2026-10-03"]); expect(p.activityDates).toHaveLength(0); });
  it("level celebration clears only the UI effect", () => { const r = engine.finishAction(empty(), empty(), [event("jump", 850, "debug_adjustment")], now); const p = engine.markLevelCelebrated(r.progress); expect(p.pendingLevelUp).toBeNull(); expect(engine.getTotalXp(p)).toBe(850); expect(engine.getCurrentLevel(engine.getTotalXp(p)).level).toBe(4); });
  it.each([["2026-10-24T21:30:00Z", 1, "2026-10-26"], ["2026-03-28T21:30:00Z", 1, "2026-03-29"], ["2026-03-28T21:30:00Z", 2, "2026-03-30"]])("virtual +%s days stays calendar-correct", (timestamp, offset, expected) => expect(getBucharestDateKey(getOffsetNow(new Date(timestamp), offset))).toBe(expected));
});
describe("partial-v2 reward eligibility", () => {
  it("journal evidence preserves first-completion eligibility when stats are missing", () => {
    const first = engine.completeLessonSession(empty(), session(7), now).progress;
    const recovered = engine.normalizeProgress({ ...first, lessonStats: {} }, now);
    expect(engine.getCompletedLessonCount(recovered)).toBe(1);
    expect(recovered.lessonStats[lesson.id].bestFirstTryCorrect).toBe(7);
    const replay = engine.completeLessonSession(recovered, session(9, "recovered-replay"), now);
    expect(replay.lesson?.firstCompletion).toBe(false);
    expect(replay.lesson?.improvementXp).toBe(8);
    expect(replay.newEvents.some(e => e.type === "lesson_perfect" || e.type === "lesson_completion" || e.type === "lesson_question_first_try")).toBe(false);
  });
});
describe("partial-v2 calendar evidence", () => {
  it("retains the latest journal date when the explicit clock anchor is missing", () => {
    const future = engine.completeDailyChallenge(engine.createEmptyProgress(onDay("2026-10-10")), engine.selectDailyChallenge("2026-10-10").correctOptionId, onDay("2026-10-10")).progress;
    const normalized = engine.normalizeProgress({ ...future, maxSeenDateKey: null, maxSeenAt: null }, onDay("2026-10-08"));
    expect(normalized.maxSeenDateKey).toBe("2026-10-10");
    expect(engine.completeDailyChallenge(normalized, engine.selectDailyChallenge("2026-10-10").correctOptionId, onDay("2026-10-08")).newEvents).toHaveLength(0);
  });
});
