import type { z } from "zod";
import type { ProgressSchema, XpEventSchema, XpEventTypeSchema, LessonStatsSchema, DailyChallengeResultSchema, SimulationSchema } from "../lib/progress-schema";
export type Level = { level: number; title: string; minXp: number };
export type LevelUp = { from: Level; to: Level; levelsGained: number };
export type ProgressState = z.infer<typeof ProgressSchema>;
export type XpEvent = z.infer<typeof XpEventSchema>;
export type XpEventType = z.infer<typeof XpEventTypeSchema>;
export type LessonStats = z.infer<typeof LessonStatsSchema>;
export type DailyChallengeResult = z.infer<typeof DailyChallengeResultSchema>;
export type SimulationState = z.infer<typeof SimulationSchema>;
export type LessonSessionResult = { lessonId: string; sessionId: string; answers: { screenId: string; selectedOptionId: string }[] };
export type StreakStatus = { current: number; longest: number; freezeAvailable: boolean };
export type XpBreakdown = { type: XpEventType; label: string; amount: number; count: number };
export type LessonRewardSummary = { firstCompletion: boolean; score: number; questionCount: number; previousBest: number; best: number; perfect: boolean; improvementXp: number };
export type DomainResult = { progress: ProgressState; newEvents: XpEvent[]; xpGained: number; xpBreakdown: XpBreakdown[]; levelBefore: Level; levelAfter: Level; levelUpCount: number; levelUp: LevelUp | null; streakBefore: number; streakAfter: number; freezeConsumed: string[]; dailyGoalCompleted: boolean; achievementsUnlocked: string[]; lesson?: LessonRewardSummary };
