export type Level = { level: number; title: string; minXp: number };
export type RewardSource = "lesson" | "perfect" | "daily" | "simulator" | "streak";
export type Reward = { source: RewardSource; key: string; xp: number };
export type LevelUp = { from: Level; to: Level; levelsGained: number };
export type RewardEvent = { type: "reward"; reward: Reward } | { type: "achievement"; id: string } | { type: "level-up"; levelUp: LevelUp };
export type AchievementState = { unlockedIds: string[]; seenToastIds: string[] };
export type DailyChallengeResult = { challengeId: string; selectedOptionId: string | null; wasCorrect: boolean | null; completedAt: string | null; xpAwarded: boolean };
export type SimulationState = { step: number; balance: number; savings: number; history: string[] };
export type LegacyStreak = { count: number; anchorDate: string; runId: string; includesAnchorActivity: boolean };
export type LessonStats = { sessionIds: string[]; lastCompletedAt: string; bestCorrectAnswers: number; questionCount: number };
export type ProgressState = {
  version: 1;
  totalXp: number;
  completedLessonIds: string[];
  awardedRewardKeys: string[];
  lessonStats: Record<string, LessonStats>;
  activityDates: string[];
  freezeDates: string[];
  longestStreak: number;
  legacyStreak: LegacyStreak | null;
  dailyChallenges: Record<string, DailyChallengeResult>;
  simulatorCompletions: string[];
  simulation: SimulationState;
  uniqueCorrectAnswers: string[];
  achievements: AchievementState;
  highestCelebratedLevel: number;
  lastLessonId: string | null;
  updatedAt: string | null;
};
export type LessonSessionResult = { lessonId: string; sessionId: string; answers: { screenId: string; selectedOptionId: string }[] };
export type DomainResult = { progress: ProgressState; xpGained: number; rewards: Reward[]; achievementsUnlocked: string[]; levelUp: LevelUp | null; events: RewardEvent[] };
export type StreakStatus = { current: number; longest: number; runId: string | null; freezeAvailable: boolean };
