import type { ReadyLesson } from "../../types/learning";
import { calc, choice, scenario } from "./builders";
export const inflationLesson: ReadyLesson = {
  id: "ce-este-inflatia", slug: "ce-este-inflatia", categoryId: "economia-pe-scurt", chapterId: "preturile-se-schimba",
  title: "Ce este inflația?", description: "Aceiași bani. Mai puține lucruri în coș.", minutes: 3, xp: 20, status: "ready",
  recapPoints: ["Inflația înseamnă o creștere generalizată a prețurilor.", "Aceeași sumă cumpără mai puțin dacă prețurile cresc.", "Un buget util folosește prețurile pe care le plătești acum."],
  sourceUrls: [{ label: "BCE · Ce este inflația?", url: "https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me-more/html/what_is_inflation.ro.html" }],
  screens: [
    { id: "intro", type: "text", title: "Același portofel. Un coș mai mic.", body: "Dacă multe prețuri cresc, aceeași sumă nu mai cumpără la fel de mult. Asta e ideea din spatele inflației.", fini: { mood: "thinking", message: "Hai să o vedem la cumpărături." }, continueLabel: "Hai să începem" },
    calc("pret", "Un leu în plus.", "Anul trecut, un produs costa 10 lei. Acum costă 11 lei.", "Cu câți lei a crescut prețul?", [1, 10, 11, 21], 1, "11 − 10 = 1 leu în plus. Este o scumpire a acestui produs; singură nu descrie toate prețurile din economie."),
    scenario("tricou", "Un tricou mai scump.", "Un singur magazin scumpește un tricou. Despre celelalte prețuri nu știm nimic.", "Este suficient ca să concluzionăm că există inflație?", ["Da, orice scumpire este inflație.", "Nu încă. Avem nevoie de evoluția prețurilor în general.", "Da, dacă tricoul este popular.", "Nu, hainele nu contează niciodată."], 1, "Inflația descrie o creștere generalizată a prețurilor. Un produs sau un magazin nu sunt suficiente pentru concluzie."),
    { id: "cos", type: "text", title: "Ne uităm la un coș, nu la un produs.", body: "Pentru a măsura inflația, se urmărește un coș de bunuri și servicii. Unele se pot ieftini chiar dacă, în ansamblu, prețurile cresc.", highlight: "Multe prețuri, privite împreună." },
    choice("putere", "Venitul tău rămâne la fel.", "Multe prețuri cresc. Ce se întâmplă cu puterea ta de cumpărare?", ["Crește: ai aceeași sumă.", "Rămâne identică: venitul nu s-a schimbat.", "Scade: aceeași sumă cumpără mai puțin.", "Scade doar dacă plătești cu numerar."], 2, "Puterea de cumpărare spune ce poți cumpăra cu banii tăi. Dacă prețurile cresc, aceeași sumă acoperă mai puțin."),
    calc("cos-mic", "La magazin, cu 50 lei.", "Un produs costa 10 lei. Acum costă 12 lei. Ai 50 lei și cumperi doar acest produs.", "Câte bucăți întregi poți cumpăra acum?", [3, 4, 5, 6], 4, "4 bucăți costă 48 lei. A cincea ar duce totalul la 60 lei, peste bugetul tău.", "bucăți"),
    scenario("buget", "Bugetul de anul trecut.", "Ai aceeași sumă lunar, dar cumpărăturile tale obișnuite costă mai mult.", "Ce te ajută să îți refaci planul?", ["Folosesc în continuare toate prețurile vechi.", "Verific cheltuielile reale și ajustez prioritățile.", "Presupun că fiecare produs s-a scumpit la fel.", "Renunț la buget: nu mai are rost."], 1, "Un plan util pornește de la prețurile de acum. Verifică propriile cheltuieli, fiindcă nu toate produsele se schimbă la fel."),
    choice("mai-lent", "Prețurile cresc mai încet.", "Inflația scade, dar rămâne pozitivă. Înseamnă că prețurile, în general, au revenit la nivelul vechi?", ["Da, inflație mai mică înseamnă prețuri mai mici.", "Da, toate scumpirile se anulează.", "Nu. În general, cresc în continuare, mai lent.", "Nu putem afla nimic despre direcția prețurilor."], 2, "O rată pozitivă mai mică înseamnă un ritm mai lent al scumpirilor. Nu o revenire automată la prețurile vechi."),
    { id: "recap", type: "text", title: "Acum vezi ce e în spatele prețului.", body: "Inflația nu înseamnă că totul se scumpește identic. Uită-te la prețurile în general, apoi la propriul coș și la ce mai acoperă bugetul tău.", fini: { mood: "happy", message: "Aceiași bani pot cumpăra lucruri diferite de la un an la altul." } },
  ],
};
