import { ComingSoonLessonSchema } from "../../types/learning-schema";

// Metadata only. Publish by importing a ReadyLesson in index.ts.
export const comingSoonLessons = ComingSoonLessonSchema.array().parse([
  {
    "id": "ce-sunt-banii",
    "slug": "ce-sunt-banii",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "ce-sunt-banii",
    "title": "Ce sunt banii",
    "description": "O idee practică: ce sunt banii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-unde-vin-banii",
    "slug": "de-unde-vin-banii",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "ce-sunt-banii",
    "title": "De unde vin banii",
    "description": "O idee practică: de unde vin banii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "valoarea-banilor-in-timp",
    "slug": "valoarea-banilor-in-timp",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "ce-sunt-banii",
    "title": "Valoarea banilor în timp",
    "description": "O idee practică: valoarea banilor în timp.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "venit-vs-cheltuieli",
    "slug": "venit-vs-cheltuieli",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "venit-si-cheltuieli",
    "title": "Venit vs. cheltuieli",
    "description": "O idee practică: venit vs. cheltuieli.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "active-vs-pasive",
    "slug": "active-vs-pasive",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "venit-si-cheltuieli",
    "title": "Active vs. pasive",
    "description": "O idee practică: active vs. pasive.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "costul-de-oportunitate",
    "slug": "costul-de-oportunitate",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "venit-si-cheltuieli",
    "title": "Costul de oportunitate",
    "description": "O idee practică: costul de oportunitate.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-vrei-de-la-bani",
    "slug": "ce-vrei-de-la-bani",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "obiective-financiare",
    "title": "Ce vrei de la bani",
    "description": "O idee practică: ce vrei de la bani.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "termen-scurt-vs-termen-lung",
    "slug": "termen-scurt-vs-termen-lung",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "obiective-financiare",
    "title": "Termen scurt vs. termen lung",
    "description": "O idee practică: termen scurt vs. termen lung.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "independenta-financiara",
    "slug": "independenta-financiara",
    "categoryId": "cum-functioneaza-banii",
    "chapterId": "obiective-financiare",
    "title": "Independența financiară",
    "description": "O idee practică: independența financiară.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "nevoie-sau-dorinta",
    "slug": "nevoie-sau-dorinta",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Nevoi vs. dorințe",
    "description": "O idee practică: nevoi vs. dorințe.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cumperi-sau-inchiriezi",
    "slug": "cumperi-sau-inchiriezi",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Cumperi sau închiriezi",
    "description": "O idee practică: cumperi sau închiriezi.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "costul-real-al-unui-produs",
    "slug": "costul-real-al-unui-produs",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Costul real al unui produs",
    "description": "O idee practică: costul real al unui produs.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cumparaturile-pe-impuls",
    "slug": "cumparaturile-pe-impuls",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "capcanele-cumparaturilor",
    "title": "Cumpărăturile pe impuls",
    "description": "O idee practică: cumpărăturile pe impuls.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "regula-48-de-ore",
    "slug": "regula-48-de-ore",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "capcanele-cumparaturilor",
    "title": "Regula celor 48 de ore",
    "description": "O idee practică: regula celor 48 de ore.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "reduceri-care-nu-sunt-reduceri",
    "slug": "reduceri-care-nu-sunt-reduceri",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "capcanele-cumparaturilor",
    "title": "Reduceri care nu sunt reduceri",
    "description": "O idee practică: reduceri care nu sunt reduceri.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-te-conving-reclamele",
    "slug": "cum-te-conving-reclamele",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "capcanele-cumparaturilor",
    "title": "Cum te conving reclamele",
    "description": "O idee practică: cum te conving reclamele.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "compara-preturile",
    "slug": "compara-preturile",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "cumperi-inteligent",
    "title": "Compară prețurile",
    "description": "O idee practică: compară prețurile.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "abonamentele",
    "slug": "abonamentele",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "cumperi-inteligent",
    "title": "Abonamentele",
    "description": "O idee practică: abonamentele.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "iesiri-cu-prietenii-fara-sa-te-golesti",
    "slug": "iesiri-cu-prietenii-fara-sa-te-golesti",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "cumperi-inteligent",
    "title": "Ieșiri cu prietenii fără să te golești",
    "description": "O idee practică: ieșiri cu prietenii fără să te golești.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-face-o-banca",
    "slug": "ce-face-o-banca",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Ce face o bancă",
    "description": "O idee practică: ce face o bancă.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "contul-curent",
    "slug": "contul-curent",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Contul curent",
    "description": "O idee practică: contul curent.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "iban",
    "slug": "iban",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "IBAN",
    "description": "O idee practică: iban.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "comisioane-bancare",
    "slug": "comisioane-bancare",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Comisioane bancare",
    "description": "O idee practică: comisioane bancare.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cardul-de-debit",
    "slug": "cardul-de-debit",
    "categoryId": "carduri-si-banca",
    "chapterId": "cardul",
    "title": "Cardul de debit",
    "description": "O idee practică: cardul de debit.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-platesti-cu-cardul",
    "slug": "cum-platesti-cu-cardul",
    "categoryId": "carduri-si-banca",
    "chapterId": "cardul",
    "title": "Cum plătești cu cardul",
    "description": "O idee practică: cum plătești cu cardul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cardul-in-strainatate",
    "slug": "cardul-in-strainatate",
    "categoryId": "carduri-si-banca",
    "chapterId": "cardul",
    "title": "Cardul în străinătate",
    "description": "O idee practică: cardul în străinătate.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "transferuri-si-plati-instant",
    "slug": "transferuri-si-plati-instant",
    "categoryId": "carduri-si-banca",
    "chapterId": "bani-in-miscare",
    "title": "Transferuri și plăți instant",
    "description": "O idee practică: transferuri și plăți instant.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "aplicatii-bancare",
    "slug": "aplicatii-bancare",
    "categoryId": "carduri-si-banca",
    "chapterId": "bani-in-miscare",
    "title": "Aplicații bancare",
    "description": "O idee practică: aplicații bancare.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "plati-online-in-siguranta",
    "slug": "plati-online-in-siguranta",
    "categoryId": "carduri-si-banca",
    "chapterId": "bani-in-miscare",
    "title": "Plăți online în siguranță",
    "description": "O idee practică: plăți online în siguranță.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },

  {
    "id": "apelul-fals-de-la-banca",
    "slug": "apelul-fals-de-la-banca",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Apelul fals de la „bancă”",
    "description": "O idee practică: apelul fals de la „bancă”.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "inselatorii-pe-retele-sociale",
    "slug": "inselatorii-pe-retele-sociale",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Înșelătorii pe rețele sociale",
    "description": "O idee practică: înșelătorii pe rețele sociale.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "magazine-false",
    "slug": "magazine-false",
    "categoryId": "siguranta-financiara",
    "chapterId": "magazine-si-oferte-false",
    "title": "Magazine false",
    "description": "O idee practică: magazine false.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "giveaway-uri-false",
    "slug": "giveaway-uri-false",
    "categoryId": "siguranta-financiara",
    "chapterId": "magazine-si-oferte-false",
    "title": "Giveaway-uri false",
    "description": "O idee practică: giveaway-uri false.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "oferte-prea-bune",
    "slug": "oferte-prea-bune",
    "categoryId": "siguranta-financiara",
    "chapterId": "magazine-si-oferte-false",
    "title": "Oferte prea bune ca să fie reale",
    "description": "O idee practică: oferte prea bune ca să fie reale.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "protejeaza-datele-cardului",
    "slug": "protejeaza-datele-cardului",
    "categoryId": "siguranta-financiara",
    "chapterId": "datele-tale",
    "title": "Protejează datele cardului",
    "description": "O idee practică: protejează datele cardului.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "furtul-de-identitate",
    "slug": "furtul-de-identitate",
    "categoryId": "siguranta-financiara",
    "chapterId": "datele-tale",
    "title": "Furtul de identitate",
    "description": "O idee practică: furtul de identitate.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-faci-daca-ai-fost-inselat",
    "slug": "ce-faci-daca-ai-fost-inselat",
    "categoryId": "siguranta-financiara",
    "chapterId": "datele-tale",
    "title": "Ce faci dacă ai fost înșelat",
    "description": "O idee practică: ce faci dacă ai fost înșelat.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },

  {
    "id": "metoda-50-30-20",
    "slug": "metoda-50-30-20",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Metoda 50/30/20",
    "description": "O idee practică: metoda 50/30/20.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "unde-dispar-banii",
    "slug": "unde-dispar-banii",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Unde dispar banii",
    "description": "O idee practică: unde dispar banii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "puterea-economisirii",
    "slug": "puterea-economisirii",
    "categoryId": "economii",
    "chapterId": "economisirea",
    "title": "Puterea economisirii",
    "description": "O idee practică: puterea economisirii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "plateste-te-primul",
    "slug": "plateste-te-primul",
    "categoryId": "economii",
    "chapterId": "economisirea",
    "title": "Plătește-te pe tine primul",
    "description": "O idee practică: plătește-te pe tine primul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "economisesti-fara-sa-te-privezi",
    "slug": "economisesti-fara-sa-te-privezi",
    "categoryId": "economii",
    "chapterId": "economisirea",
    "title": "Economisești fără să te privezi",
    "description": "O idee practică: economisești fără să te privezi.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },

  {
    "id": "obiective-de-economisire",
    "slug": "obiective-de-economisire",
    "categoryId": "economii",
    "chapterId": "siguranta-ta-financiara",
    "title": "Obiective de economisire",
    "description": "O idee practică: obiective de economisire.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cont-de-economii-vs-numerar",
    "slug": "cont-de-economii-vs-numerar",
    "categoryId": "economii",
    "chapterId": "siguranta-ta-financiara",
    "title": "Cont de economii vs. numerar",
    "description": "O idee practică: cont de economii vs. numerar.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "primul-contract-de-munca",
    "slug": "primul-contract-de-munca",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Primul contract de muncă",
    "description": "O idee practică: primul contract de muncă.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "munca-part-time-si-student",
    "slug": "munca-part-time-si-student",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Muncă part-time și student",
    "description": "O idee practică: muncă part-time și student.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "negocierea-salariului",
    "slug": "negocierea-salariului",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Negocierea salariului",
    "description": "O idee practică: negocierea salariului.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "fluturasul-de-salariu",
    "slug": "fluturasul-de-salariu",
    "categoryId": "primul-job",
    "chapterId": "salariul",
    "title": "Fluturașul de salariu",
    "description": "O idee practică: fluturașul de salariu.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "salariul-minim",
    "slug": "salariul-minim",
    "categoryId": "primul-job",
    "chapterId": "salariul",
    "title": "Salariul minim",
    "description": "O idee practică: salariul minim.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "tichete-si-beneficii",
    "slug": "tichete-si-beneficii",
    "categoryId": "primul-job",
    "chapterId": "salariul",
    "title": "Tichete și beneficii",
    "description": "O idee practică: tichete și beneficii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-ce-platim-taxe",
    "slug": "de-ce-platim-taxe",
    "categoryId": "primul-job",
    "chapterId": "taxele",
    "title": "De ce plătim taxe",
    "description": "O idee practică: de ce plătim taxe.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "taxele-pe-salariu",
    "slug": "taxele-pe-salariu",
    "categoryId": "primul-job",
    "chapterId": "taxele",
    "title": "Taxele pe salariu",
    "description": "O idee practică: taxele pe salariu.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "declaratia-unica",
    "slug": "declaratia-unica",
    "categoryId": "primul-job",
    "chapterId": "taxele",
    "title": "Declarația unică",
    "description": "O idee practică: declarația unică.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "angajat-vs-pfa",
    "slug": "angajat-vs-pfa",
    "categoryId": "primul-job",
    "chapterId": "taxele",
    "title": "Angajat vs. PFA",
    "description": "O idee practică: angajat vs. pfa.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "primul-salariu",
    "slug": "primul-salariu",
    "categoryId": "primul-job",
    "chapterId": "dupa-salariu",
    "title": "Ce faci cu primul salariu",
    "description": "O idee practică: ce faci cu primul salariu.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "mutatul-de-acasa",
    "slug": "mutatul-de-acasa",
    "categoryId": "pe-cont-propriu",
    "chapterId": "casa-ta",
    "title": "Mutatul de acasă",
    "description": "O idee practică: mutatul de acasă.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "chirie-si-contract-de-inchiriere",
    "slug": "chirie-si-contract-de-inchiriere",
    "categoryId": "pe-cont-propriu",
    "chapterId": "casa-ta",
    "title": "Chirie și contract de închiriere",
    "description": "O idee practică: chirie și contract de închiriere.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "utilitati",
    "slug": "utilitati",
    "categoryId": "pe-cont-propriu",
    "chapterId": "casa-ta",
    "title": "Utilități",
    "description": "O idee practică: utilități.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cumperi-casa-sau-inchiriezi",
    "slug": "cumperi-casa-sau-inchiriezi",
    "categoryId": "pe-cont-propriu",
    "chapterId": "casa-ta",
    "title": "Cumperi casă sau închiriezi",
    "description": "O idee practică: cumperi casă sau închiriezi.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "primul-telefon-sau-laptop",
    "slug": "primul-telefon-sau-laptop",
    "categoryId": "pe-cont-propriu",
    "chapterId": "cumparaturi-mari",
    "title": "Primul telefon sau laptop",
    "description": "O idee practică: primul telefon sau laptop.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "costul-real-al-unei-masini",
    "slug": "costul-real-al-unei-masini",
    "categoryId": "pe-cont-propriu",
    "chapterId": "cumparaturi-mari",
    "title": "Costul real al unei mașini",
    "description": "O idee practică: costul real al unei mașini.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "asigurari",
    "slug": "asigurari",
    "categoryId": "pe-cont-propriu",
    "chapterId": "cumparaturi-mari",
    "title": "Asigurări",
    "description": "O idee practică: asigurări.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cumparaturile-din-supermarket",
    "slug": "cumparaturile-din-supermarket",
    "categoryId": "pe-cont-propriu",
    "chapterId": "viata-de-zi-cu-zi",
    "title": "Cumpărăturile din supermarket",
    "description": "O idee practică: cumpărăturile din supermarket.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "vacanta",
    "slug": "vacanta",
    "categoryId": "pe-cont-propriu",
    "chapterId": "viata-de-zi-cu-zi",
    "title": "Vacanța",
    "description": "O idee practică: vacanța.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cheltuieli-neprevazute",
    "slug": "cheltuieli-neprevazute",
    "categoryId": "pe-cont-propriu",
    "chapterId": "viata-de-zi-cu-zi",
    "title": "Cheltuieli neprevăzute",
    "description": "O idee practică: cheltuieli neprevăzute.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "banii-intr-o-relatie",
    "slug": "banii-intr-o-relatie",
    "categoryId": "pe-cont-propriu",
    "chapterId": "viata-de-zi-cu-zi",
    "title": "Banii într-o relație",
    "description": "O idee practică: banii într-o relație.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "fomo-si-cheltuieli",
    "slug": "fomo-si-cheltuieli",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "presiunea-din-jur",
    "title": "FOMO și cheltuieli",
    "description": "O idee practică: fomo și cheltuieli.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "presiunea-sociala",
    "slug": "presiunea-sociala",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "presiunea-din-jur",
    "title": "Presiunea socială",
    "description": "O idee practică: presiunea socială.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-vorbesti-despre-bani",
    "slug": "cum-vorbesti-despre-bani",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "presiunea-din-jur",
    "title": "Cum vorbești despre bani",
    "description": "O idee practică: cum vorbești despre bani.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cheltuieli-emotionale",
    "slug": "cheltuieli-emotionale",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "creierul-si-banii",
    "title": "Cheltuieli emoționale",
    "description": "O idee practică: cheltuieli emoționale.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "efectul-de-ancorare",
    "slug": "efectul-de-ancorare",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "creierul-si-banii",
    "title": "Efectul de ancorare",
    "description": "O idee practică: efectul de ancorare.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "gandirea-pe-termen-lung",
    "slug": "gandirea-pe-termen-lung",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "obiceiuri",
    "title": "Gândirea pe termen lung",
    "description": "O idee practică: gândirea pe termen lung.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "obiceiuri-bune-cu-banii",
    "slug": "obiceiuri-bune-cu-banii",
    "categoryId": "de-ce-cheltuim-cum-cheltuim",
    "chapterId": "obiceiuri",
    "title": "Obiceiuri bune cu banii",
    "description": "O idee practică: obiceiuri bune cu banii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-ce-cresc-preturile",
    "slug": "de-ce-cresc-preturile",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "De ce cresc prețurile",
    "description": "O idee practică: de ce cresc prețurile.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cerere-si-oferta",
    "slug": "cerere-si-oferta",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "Cerere și ofertă",
    "description": "O idee practică: cerere și ofertă.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-dobanda",
    "slug": "ce-este-dobanda",
    "categoryId": "economia-pe-scurt",
    "chapterId": "dobanzi",
    "title": "Ce este dobânda",
    "description": "O idee practică: ce este dobânda.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cine-stabileste-dobanzile",
    "slug": "cine-stabileste-dobanzile",
    "categoryId": "economia-pe-scurt",
    "chapterId": "dobanzi",
    "title": "Cine stabilește dobânzile",
    "description": "O idee practică: cine stabilește dobânzile.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-face-bnr",
    "slug": "ce-face-bnr",
    "categoryId": "economia-pe-scurt",
    "chapterId": "dobanzi",
    "title": "Banca centrală (BNR)",
    "description": "O idee practică: banca centrală (bnr).",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "pib",
    "slug": "pib",
    "categoryId": "economia-pe-scurt",
    "chapterId": "economia-mare",
    "title": "PIB-ul",
    "description": "O idee practică: pib-ul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "somajul",
    "slug": "somajul",
    "categoryId": "economia-pe-scurt",
    "chapterId": "economia-mare",
    "title": "Șomajul",
    "description": "O idee practică: șomajul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "recesiune-si-criza",
    "slug": "recesiune-si-criza",
    "categoryId": "economia-pe-scurt",
    "chapterId": "economia-mare",
    "title": "Recesiune și criză",
    "description": "O idee practică: recesiune și criză.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cursul-valutar",
    "slug": "cursul-valutar",
    "categoryId": "economia-pe-scurt",
    "chapterId": "valute",
    "title": "Cursul valutar",
    "description": "O idee practică: cursul valutar.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "leul-si-euro",
    "slug": "leul-si-euro",
    "categoryId": "economia-pe-scurt",
    "chapterId": "valute",
    "title": "Leul și euro",
    "description": "O idee practică: leul și euro.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-creditul",
    "slug": "ce-este-creditul",
    "categoryId": "credite-si-datorii",
    "chapterId": "bazele-creditului",
    "title": "Ce este creditul",
    "description": "O idee practică: ce este creditul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "dobanda-la-credit-si-dae",
    "slug": "dobanda-la-credit-si-dae",
    "categoryId": "credite-si-datorii",
    "chapterId": "bazele-creditului",
    "title": "Dobânda la credit și DAE",
    "description": "O idee practică: dobânda la credit și dae.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },

  {
    "id": "cardul-de-credit",
    "slug": "cardul-de-credit",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-de-zi-cu-zi",
    "title": "Cardul de credit",
    "description": "O idee practică: cardul de credit.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "plata-in-rate-si-cumpara-acum-plateste-mai-tarziu",
    "slug": "plata-in-rate-si-cumpara-acum-plateste-mai-tarziu",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-de-zi-cu-zi",
    "title": "Plata în rate și „cumpără acum, plătește mai târziu”",
    "description": "O idee practică: plata în rate și „cumpără acum, plătește mai târziu”.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "creditele-rapide-ifn",
    "slug": "creditele-rapide-ifn",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-de-zi-cu-zi",
    "title": "Creditele rapide (IFN)",
    "description": "O idee practică: creditele rapide (ifn).",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "girant-si-garantii",
    "slug": "girant-si-garantii",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-mari-si-riscuri",
    "title": "Girant și garanții",
    "description": "O idee practică: girant și garanții.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "creditul-ipotecar",
    "slug": "creditul-ipotecar",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-mari-si-riscuri",
    "title": "Creditul ipotecar",
    "description": "O idee practică: creditul ipotecar.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-iesi-din-datorii",
    "slug": "cum-iesi-din-datorii",
    "categoryId": "credite-si-datorii",
    "chapterId": "credite-mari-si-riscuri",
    "title": "Cum ieși din datorii",
    "description": "O idee practică: cum ieși din datorii.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "idei-de-venit-side-hustle",
    "slug": "idei-de-venit-side-hustle",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "primii-bani",
    "title": "Idei de venit (side hustle)",
    "description": "O idee practică: idei de venit (side hustle).",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "freelancing",
    "slug": "freelancing",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "primii-bani",
    "title": "Freelancing",
    "description": "O idee practică: freelancing.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "vinzi-online",
    "slug": "vinzi-online",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "primii-bani",
    "title": "Vinzi online",
    "description": "O idee practică: vinzi online.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "costuri-si-profit",
    "slug": "costuri-si-profit",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "cum-merge-o-afacere",
    "title": "Costuri și profit",
    "description": "O idee practică: costuri și profit.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-stabilesti-pretul",
    "slug": "cum-stabilesti-pretul",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "cum-merge-o-afacere",
    "title": "Cum stabilești prețul",
    "description": "O idee practică: cum stabilești prețul.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "primii-clienti",
    "slug": "primii-clienti",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "cum-merge-o-afacere",
    "title": "Primii clienți",
    "description": "O idee practică: primii clienți.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "taxele-cand-ai-venit-propriu",
    "slug": "taxele-cand-ai-venit-propriu",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "taxe-si-realitate",
    "title": "Taxele când ai venit propriu",
    "description": "O idee practică: taxele când ai venit propriu.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "esecul-in-afaceri",
    "slug": "esecul-in-afaceri",
    "categoryId": "afaceri-si-venituri-extra",
    "chapterId": "taxe-si-realitate",
    "title": "Eșecul în afaceri",
    "description": "O idee practică: eșecul în afaceri.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-ce-investim",
    "slug": "de-ce-investim",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "bazele",
    "title": "De ce investim",
    "description": "O idee practică: de ce investim.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "risc-si-randament",
    "slug": "risc-si-randament",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "bazele",
    "title": "Risc și randament",
    "description": "O idee practică: risc și randament.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },

  {
    "id": "diversificarea",
    "slug": "diversificarea",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "bazele",
    "title": "Diversificarea",
    "description": "O idee practică: diversificarea.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "actiuni",
    "slug": "actiuni",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "instrumente",
    "title": "Acțiuni",
    "description": "O idee practică: acțiuni.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "obligatiuni-si-titluri-de-stat",
    "slug": "obligatiuni-si-titluri-de-stat",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "instrumente",
    "title": "Obligațiuni și titluri de stat",
    "description": "O idee practică: obligațiuni și titluri de stat.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "etf-uri-si-fonduri",
    "slug": "etf-uri-si-fonduri",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "instrumente",
    "title": "ETF-uri și fonduri",
    "description": "O idee practică: etf-uri și fonduri.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-functioneaza-bursa",
    "slug": "cum-functioneaza-bursa",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "instrumente",
    "title": "Cum funcționează bursa",
    "description": "O idee practică: cum funcționează bursa.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "investesti-vs-speculezi",
    "slug": "investesti-vs-speculezi",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "atentie-la-capcane",
    "title": "Investești vs. speculezi",
    "description": "O idee practică: investești vs. speculezi.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "crypto-ce-trebuie-sa-stii",
    "slug": "crypto-ce-trebuie-sa-stii",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "atentie-la-capcane",
    "title": "Crypto: ce trebuie să știi",
    "description": "O idee practică: crypto: ce trebuie să știi.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "piramide-si-scheme-bani-rapizi",
    "slug": "piramide-si-scheme-bani-rapizi",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "atentie-la-capcane",
    "title": "Piramide și scheme „bani rapizi”",
    "description": "O idee practică: piramide și scheme „bani rapizi”.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "pensiile-pilonul-2-si-3",
    "slug": "pensiile-pilonul-2-si-3",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "pe-termen-lung",
    "title": "Pensiile (Pilonul 2 și 3)",
    "description": "O idee practică: pensiile (pilonul 2 și 3).",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cum-incepi-cu-sume-mici",
    "slug": "cum-incepi-cu-sume-mici",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "pe-termen-lung",
    "title": "Cum începi cu sume mici",
    "description": "O idee practică: cum începi cu sume mici.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "taxe-pe-castigurile-din-investitii",
    "slug": "taxe-pe-castigurile-din-investitii",
    "categoryId": "investitii-de-la-zero",
    "chapterId": "pe-termen-lung",
    "title": "Taxe pe câștigurile din investiții",
    "description": "O idee practică: taxe pe câștigurile din investiții.",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  }
]);

// Retired catalog IDs remain resolvable; they do not affect curriculum counts/progress.
export const legacyLessons = ComingSoonLessonSchema.array().parse([
  {
    "id": "ce-este-salariul",
    "slug": "ce-este-salariul",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Ce este salariul?",
    "description": "O idee practică: ce este salariul?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-intra-in-cont",
    "slug": "ce-intra-in-cont",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Ce intră efectiv în cont?",
    "description": "O idee practică: ce intră efectiv în cont?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-fluturasul",
    "slug": "ce-este-fluturasul",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Ce este fluturașul?",
    "description": "O idee practică: ce este fluturașul?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "taxe-si-contributii",
    "slug": "taxe-si-contributii",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Taxe și contribuții",
    "description": "O idee practică: taxe și contribuții",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cas-si-cass",
    "slug": "cas-si-cass",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "CAS și CASS pe înțelesul tău",
    "description": "O idee practică: cas și cass pe înțelesul tău",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "brut-sau-net",
    "slug": "brut-sau-net",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Brut sau net?",
    "description": "O idee practică: brut sau net?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "compari-doua-oferte",
    "slug": "compari-doua-oferte",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Cum compari două oferte",
    "description": "O idee practică: cum compari două oferte",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "inainte-sa-accepti",
    "slug": "inainte-sa-accepti",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Ce întrebi înainte să accepți?",
    "description": "O idee practică: ce întrebi înainte să accepți?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cand-intra-salariul",
    "slug": "cand-intra-salariul",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Când intră salariul?",
    "description": "O idee practică: când intră salariul?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "bonusuri-si-beneficii",
    "slug": "bonusuri-si-beneficii",
    "categoryId": "primul-job",
    "chapterId": "primul-job",
    "title": "Bonusuri și beneficii",
    "description": "O idee practică: bonusuri și beneficii",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-un-buget",
    "slug": "ce-este-un-buget",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Ce este un buget?",
    "description": "O idee practică: ce este un buget?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "venituri-vs-cheltuieli",
    "slug": "venituri-vs-cheltuieli",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Venituri vs. cheltuieli",
    "description": "O idee practică: venituri vs. cheltuieli",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "fixe-vs-variabile",
    "slug": "fixe-vs-variabile",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Cheltuieli fixe vs. variabile",
    "description": "O idee practică: cheltuieli fixe vs. variabile",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "costul-abonamentului",
    "slug": "costul-abonamentului",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Cât costă de fapt un abonament?",
    "description": "O idee practică: cât costă de fapt un abonament?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "planul-lunii",
    "slug": "planul-lunii",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Cum îți planifici o lună",
    "description": "O idee practică: cum îți planifici o lună",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ramai-fara-bani",
    "slug": "ramai-fara-bani",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "De ce rămâi fără bani?",
    "description": "O idee practică: de ce rămâi fără bani?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "setezi-o-limita",
    "slug": "setezi-o-limita",
    "categoryId": "bani-de-zi-cu-zi",
    "chapterId": "nevoi-si-dorinte",
    "title": "Cum îți setezi o limită",
    "description": "O idee practică: cum îți setezi o limită",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cont-bancar",
    "slug": "cont-bancar",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Ce este un cont bancar?",
    "description": "O idee practică: ce este un cont bancar?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-un-card",
    "slug": "ce-este-un-card",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Ce este un card?",
    "description": "O idee practică: ce este un card?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "card-debit-vs-credit",
    "slug": "card-debit-vs-credit",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Debit vs. credit",
    "description": "O idee practică: debit vs. credit",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "contactless",
    "slug": "contactless",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Contactless, pe scurt",
    "description": "O idee practică: contactless, pe scurt",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "retrageri-numerar",
    "slug": "retrageri-numerar",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Retrageri de numerar",
    "description": "O idee practică: retrageri de numerar",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "trimiti-bani",
    "slug": "trimiti-bani",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Cum trimiți bani?",
    "description": "O idee practică: cum trimiți bani?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "transfer-instant",
    "slug": "transfer-instant",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Ce este un transfer instant?",
    "description": "O idee practică: ce este un transfer instant?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "verifici-transferul",
    "slug": "verifici-transferul",
    "categoryId": "carduri-si-banca",
    "chapterId": "contul-tau",
    "title": "Ce verifici înainte să trimiți?",
    "description": "O idee practică: ce verifici înainte să trimiți?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-ce-economisim",
    "slug": "de-ce-economisim",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "De ce economisim?",
    "description": "O idee practică: de ce economisim?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "prima-tinta",
    "slug": "prima-tinta",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Prima ta țintă",
    "description": "O idee practică: prima ta țintă",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "ce-este-fondul",
    "slug": "ce-este-fondul",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Ce este fondul de siguranță?",
    "description": "O idee practică: ce este fondul de siguranță?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cat-pui-deoparte",
    "slug": "cat-pui-deoparte",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Cât ar trebui să ai?",
    "description": "O idee practică: cât ar trebui să ai?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cand-folosesti-fondul",
    "slug": "cand-folosesti-fondul",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Când îl folosești?",
    "description": "O idee practică: când îl folosești?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "dobanda-simpla",
    "slug": "dobanda-simpla",
    "categoryId": "economii",
    "chapterId": "bugetul",
    "title": "Dobândă simplă",
    "description": "O idee practică: dobândă simplă",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "semne-scam",
    "slug": "semne-scam",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Semnele unui scam",
    "description": "O idee practică: semnele unui scam",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "mesaje-false",
    "slug": "mesaje-false",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Mesaje false",
    "description": "O idee practică: mesaje false",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "pin",
    "slug": "pin",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "PIN-ul e doar al tău",
    "description": "O idee practică: pin-ul e doar al tău",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cvv",
    "slug": "cvv",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Ce este CVV-ul?",
    "description": "O idee practică: ce este cvv-ul?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "date-private",
    "slug": "date-private",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Ce nu dai niciodată altcuiva",
    "description": "O idee practică: ce nu dai niciodată altcuiva",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "bani-trimisi-gresit",
    "slug": "bani-trimisi-gresit",
    "categoryId": "siguranta-financiara",
    "chapterId": "mesaje-si-apeluri-false",
    "title": "Ce faci dacă ai trimis bani greșit?",
    "description": "O idee practică: ce faci dacă ai trimis bani greșit?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "puterea-de-cumparare",
    "slug": "puterea-de-cumparare",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "Puterea de cumpărare",
    "description": "O idee practică: puterea de cumpărare",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "produs-mai-scump",
    "slug": "produs-mai-scump",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "De ce un produs devine mai scump?",
    "description": "O idee practică: de ce un produs devine mai scump?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "toata-lumea-vrea",
    "slug": "toata-lumea-vrea",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "Când toată lumea vrea același lucru",
    "description": "O idee practică: când toată lumea vrea același lucru",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "recesiune",
    "slug": "recesiune",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "Ce este o recesiune?",
    "description": "O idee practică: ce este o recesiune?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "de-ce-conteaza-dobanzile",
    "slug": "de-ce-conteaza-dobanzile",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "De ce contează dobânzile?",
    "description": "O idee practică: de ce contează dobânzile?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "cine-creeaza-banii",
    "slug": "cine-creeaza-banii",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "Cine creează banii?",
    "description": "O idee practică: cine creează banii?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  },
  {
    "id": "dobanda-se-schimba",
    "slug": "dobanda-se-schimba",
    "categoryId": "economia-pe-scurt",
    "chapterId": "preturi",
    "title": "De ce se schimbă dobânda?",
    "description": "O idee practică: de ce se schimbă dobânda?",
    "minutes": 3,
    "xp": 20,
    "status": "coming-soon"
  }
]);
