import type { ReadyLesson } from "../../types/learning";
import { lei, roFacts, salaryExample as e } from "../ro-facts";
import { calc, choice, scenario } from "./builders";

export const salaryLesson: ReadyLesson = {
  id: "salariu-brut-vs-net", slug: "salariu-brut-vs-net", categoryId: "primul-job", chapterId: "primul-tau-salariu",
  title: "Salariu brut vs. net", description: "Înțelege unde merg banii dintre ofertă și cont.", minutes: 4, xp: 30, status: "ready",
  recapPoints: ["Brut = înainte de taxe și contribuții.", "Net = suma rămasă pentru tine. Pe ea îți bazezi bugetul.", "Clarifică brutul, netul, perioada și bonusul înainte să accepți."],
  sourceUrls: roFacts.sources,
  screens: [
    { id: "intro", type: "text", title: "Ai primul job. Dar cât primești?", body: "O ofertă mare pe hârtie nu spune mereu câți bani ajung la tine. Hai să urmărim drumul salariului, din anunț până în cont.", fini: { mood: "thinking", message: "Ține minte întrebarea asta: brut sau net?" }, continueLabel: "Hai să începem" },
    scenario("anunt", "O sumă, un detaliu lipsă.", "Anunțul spune: «Salariu 5.000 lei pe lună».", "Ce informație îți lipsește ca să știi cât primești?", ["Dacă suma este brută sau netă.", "Ziua exactă în care intră salariul.", "Dacă plata se face la aceeași bancă.", "Dacă salariul se renegociază anual."], 0, "Brut sau net schimbă sensul sumei. Data plății e utilă, dar nu îți spune câți bani rămân pentru tine."),
    { id: "definitii", type: "text", title: "Brutul e startul. Netul e ce rămâne.", body: "Brutul este suma înainte de taxe și contribuții. După rețineri rămâne netul, banii pe care te bazezi pentru cheltuielile tale.", highlight: "Brut → rețineri → net" },
    choice("contract", "Ai semnat pentru 5.000 lei brut.", "Ce ai stabilit cu angajatorul?", ["Suma garantată în cont.", "Suma înainte de taxe și contribuții.", "Costul total al firmei cu postul.", "Salariul plus orice bonus posibil."], 1, "Ai stabilit brutul. Cere și o estimare a netului pentru situația ta, ca să știi la ce să te aștepți."),
    scenario("perioada", "4.000 lei net. Pentru cât timp?", "O ofertă pentru un proiect spune doar «4.000 lei net».", "Poți compara deja suma cu un salariu lunar?", ["Da, net înseamnă automat lunar.", "Da, dacă plata vine pe card.", "Nu încă. Confirm și perioada plătită.", "Nu, veniturile din proiecte nu se pot compara."], 2, "Ai nevoie de aceeași perioadă pentru o comparație corectă. Net descrie suma după rețineri, nu cât de des o primești."),
    choice("retineri", "Unde merge diferența?", "Ce explică, în mod obișnuit, diferența dintre brut și net?", ["Un comision pentru încasarea salariului.", "Contribuțiile sociale și impozitul.", "Doar contribuții plătite separat de firmă.", "O rezervă pe care firma o restituie anual."], 1, "O parte merge către pensii și sănătate, iar impozitul pe venit merge la bugetul public. Nu este un comision bancar."),
    { id: "contributii", type: "text", title: "Două nume, două roluri.", body: "Contribuția pentru pensie se numește CAS. Contribuția pentru sănătate se numește CASS. Într-un contract obișnuit, angajatorul calculează, reține și plătește aceste sume.", fini: { mood: "neutral", message: "Un S în plus, un rol diferit." } },
    { ...choice("cas-cass", "Citești două rânduri pe fluturaș.", "Care asociere te ajută să le înțelegi?", ["CAS: sănătate. CASS: pensie.", "CAS: pensie. CASS: sănătate.", "Ambele sunt comisioane bancare.", "CAS: impozit. CASS: bonus."], 1, "CAS se leagă de pensii, CASS de sănătate. Sunt contribuții diferite de impozitul pe venit."), feedbackFini: { mood: "encouraging", message: "Nu trebuie să știi fiscalitate ca să înțelegi propriul salariu." } },
    { id: "angajator", type: "true-false", title: "Mai ai un drum de făcut?", question: "Ai un contract obișnuit la un angajator din România. Trebuie să trimiți tu contribuțiile din net, după fiecare salariu.", correctAnswer: false, explanation: "În situația obișnuită, angajatorul reține și plătește taxele salariale. Netul este suma rămasă după acele rețineri." },
    { id: "exemplu", type: "text", title: "Un exemplu, pas cu pas.", body: `${roFacts.salary.assumptions} Pornim de la ${lei(e.gross)} brut: CAS ${roFacts.salary.casRate * 100}%, CASS ${roFacts.salary.cassRate * 100}%, apoi impozit ${roFacts.salary.incomeTaxRate * 100}% pe ce rămâne.`, highlight: `${lei(e.gross)} brut`, fini: { mood: "encouraging", message: "Nu trebuie să memorezi procentele. Urmărește ordinea." } },
    calc("dupa-contributii", "Mai întâi, contribuțiile.", `Brut: ${lei(e.gross)}. CAS: ${lei(e.cas)}. CASS: ${lei(e.cass)}.`, "Cât rămâne înainte de impozit?", [e.gross - e.cas, e.taxBase, e.gross - e.cass, e.net], e.taxBase, `${lei(e.gross)} − ${lei(e.cas)} − ${lei(e.cass)} = ${lei(e.taxBase)}. Încă nu e netul: urmează impozitul.`),
    choice("baza-impozit", "Impozitul vine după contribuții.", "În acest exemplu fără deduceri, pe ce sumă calculăm impozitul?", [lei(e.gross), lei(e.net), lei(e.taxBase), lei(e.cas + e.cass)], 2, `Îl calculăm pe suma rămasă după contribuții: ${lei(e.taxBase)}. Nu direct pe tot brutul.`),
    calc("net", "Acum, ce ajunge la tine?", `După contribuții rămân ${lei(e.taxBase)}. Impozitul este ${lei(e.tax)}.`, "Care este netul exemplului?", [e.taxBase, e.net, e.gross - e.tax, e.net - e.tax], e.net, `${lei(e.taxBase)} − ${lei(e.tax)} = ${lei(e.net)} net. Deducerile, scutirile sau alte rețineri ar putea schimba calculul real.`),
    choice("deducere", "Un detaliu care poate ajuta.", "O deducere eligibilă reduce suma pe care se calculează impozitul. Ce poate însemna asta?", ["Un impozit mai mic și un net mai mare.", "Un brut automat mai mare.", "Toate contribuțiile dispar.", "Firma îți poate promite orice net."], 0, "Deducerea poate reduce impozitul. Nu șterge automat contribuțiile și se aplică doar când îndeplinești condițiile."),
    scenario("tanar", "Ai 20 de ani și primul contract.", `Există o deducere suplimentară pentru tineri de până la ${roFacts.salary.youthDeductionMaxAge} de ani, în condițiile legii.`, "Ce întrebi persoana care calculează salariile?", ["Vârsta mea înseamnă că nu plătesc taxe?", "Sunt eligibil pentru deducere în situația mea?", "Pot să aleg eu contribuțiile?", "Deducerea îmi mărește automat brutul?"], 1, "Vârsta singură nu înseamnă salariu fără taxe. Eligibilitatea depinde și de venit și de condițiile pentru funcția de bază."),
    scenario("fluturas", "Găsește banii tăi.", `Mini-fluturaș simplificat: brut ${lei(e.gross)}, CAS −${lei(e.cas)}, CASS −${lei(e.cass)}, impozit −${lei(e.tax)}, net de plată ${lei(e.net)}.`, "Ce rând verifici pentru suma care ajunge în cont, fără alte rețineri?", ["Brutul: suma din contract.", "CAS + CASS: contribuțiile tale.", "Impozitul: suma plătită statului.", `Net de plată: ${lei(e.net)}.`], 3, "Caută netul de plată, nu brutul. Pe un fluturaș real verifică și avansuri, popriri sau alte rețineri, dacă există."),
    scenario("oferte", "Două oferte, aceeași lună.", `A: ${lei(e.gross)} brut, net estimat ${lei(e.net)} în exemplul nostru. B: ${lei(e.net + 220)} net confirmat.`, "Care lasă mai mult în cont, dacă estimarea pentru A este confirmată?", ["A, fiindcă brutul este mai mare.", "B, cu 220 lei mai mult.", "A, fiindcă taxele se adaugă la net.", "Sunt egale: ambele sunt salarii."], 1, `Comparăm net cu net: ${lei(e.net + 220)} față de ${lei(e.net)}. Numărul mai mare din anunț nu câștigă automat.`),
    choice("cost-firma", "Salariu sau buget total?", "Firma spune: «Bugetul total pentru post este 8.000 lei». Ce clarifici?", ["Este brutul meu sau costul total al firmei?", "În ce zi primesc cei 8.000 lei net?", "Pot cheltui tot bugetul firmei?", "Înseamnă că nu se mai rețin contribuții?"], 0, "Costul total poate include contribuții ale angajatorului peste brut. Nu este automat nici brutul tău, nici netul de pe card."),
    scenario("beneficii", "Același net, oferte diferite.", "A: 4.000 lei net, 8 ore/zi. B: 4.000 lei net, 6 ore/zi și tichete de masă.", "Poți spune că ofertele sunt identice?", ["Da, netul este singurul lucru care contează.", "Da, tichetele sunt cash pentru orice cheltuială.", "Nu. Compar și timpul, responsabilitățile și beneficiile.", "Nu, oferta cu mai multe ore e mereu mai bună."], 2, "Netul este o parte din ofertă. Tichetele au utilizări specifice, iar programul și responsabilitățile contează pentru alegerea ta."),
    { id: "bonus", type: "true-false", title: "Nu te baza pe un «până la».", question: "«Până la 5.000 lei net, cu bonus» garantează că primești 5.000 lei în fiecare lună.", correctAnswer: false, explanation: "Bonusul poate avea condiții. Cere salariul fix și regulile pentru partea variabilă înainte să îți faci planul." },
    choice("buget", "Îți planifici luna.", `Ai ${lei(e.gross)} brut și ${lei(e.net)} net fix confirmat, fără bonusuri. Pe ce sumă îți bazezi bugetul?`, [lei(e.gross), `${lei(e.net)} plus bonusul posibil`, lei(e.net), "Costul total al firmei"], 2, "Chiria, transportul și celelalte cheltuieli se plătesc din net. Un bonus nesigur nu este o bază bună pentru costurile recurente."),
    calc("bani-ramasi", "Un plan mic, dar real.", "Din net ai pus deoparte 500 lei pentru cheltuieli de zi cu zi. Cheltui 120 lei pe transport și 80 lei pe un abonament.", "Cât mai rămâne din cei 500 lei?", [200, 300, 320, 380], 300, "500 − 120 − 80 = 300 lei. Acesta e un calcul din banii disponibili, nu din brutul de pe hârtie."),
    scenario("prima-luna", "Primul salariu e mai mic.", "Ai început la jumătatea lunii. În cont apare mai puțin decât netul estimat pentru o lună întreagă.", "Care este pasul util?", ["Presupun imediat că oferta a fost falsă.", "Verific perioada plătită și fluturașul cu HR.", "Compar transferul doar cu brutul din contract.", "Aștept fără să cer nicio explicație."], 1, "Prima plată poate acoperi doar o parte din lună. Verifică zilele plătite și reținerile; dacă ceva nu se leagă, cere explicații."),
    scenario("recap", "Ești gata să răspunzi recruiter-ului.", "Primești mesajul: «6.000 lei + bonus. Te bagi?»", "Ce răspuns te ajută înainte să accepți?", ["Da, suma e mai mare decât mă așteptam.", "Îmi confirmi brutul fix, netul estimat, programul și condițiile bonusului?", "Dacă există bonus, tot salariul e garantat, nu?", "Accept și clarific sumele după prima plată."], 1, "Cere oferta în scris și verifică dacă se regăsește în contract. Brutul, netul, perioada și bonusul îți dau o bază reală pentru decizie."),
  ],
};
